openapi: 3.0.0
info:
  description: Go Gretzky is committed to offering you an outstanding range of world
    class hockey products
  title: GoGretzky API
  version: 1.0.0
servers:
- url: https://api.example.com
paths:
  /:
    get:
      operationId: root_get
      responses:
        "200":
          content:
            application/json:
              schema:
                example: Welcome to the GoGretzky API
                type: string
                x-content-type: application/json
          description: Welcome to the GoGretzky API
      summary: Welcome to the GoGretzky API
      x-accepts: application/json
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /user:
    get:
      operationId: user_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_body'
          description: Information of the logged in user
      security:
      - bearerAuth: []
      summary: Get the information about the logged in user
      x-openapi-router-controller: openapi_server.controllers.user_controller
      x-accepts: application/json
    post:
      operationId: user_post
      responses:
        "200":
          description: Successfully added user
      security:
      - bearerAuth: []
      summary: Add a user
      x-openapi-router-controller: openapi_server.controllers.user_controller
      x-contentType: application/json
      x-accepts: application/json
  /user/address:
    get:
      operationId: user_address_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Home address of the logged in user
      security:
      - bearerAuth: []
      summary: Get the home address of the logged in user
      x-openapi-router-controller: openapi_server.controllers.address_controller
      x-accepts: application/json
    post:
      operationId: user_address_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_address_body'
      responses:
        "201":
          description: Successfully added home address to the logged in user
      security:
      - bearerAuth: []
      summary: Add a home address to the logged in user
      x-openapi-router-controller: openapi_server.controllers.address_controller
      x-contentType: application/json
      x-accepts: application/json
  /user/child:
    post:
      operationId: user_child_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_child_body'
      responses:
        "200":
          description: Successfully added child to the logged in user
      security:
      - bearerAuth: []
      summary: Add a child to the logged in user
      x-openapi-router-controller: openapi_server.controllers.child_controller
      x-contentType: application/json
      x-accepts: application/json
  /user/child/{child_id}:
    get:
      operationId: user_child_child_id_get
      parameters:
      - description: Id of the child to get
        explode: false
        in: path
        name: child_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_child_body'
          description: Child information
      security:
      - bearerAuth: []
      summary: Get the child by id
      x-openapi-router-controller: openapi_server.controllers.child_controller
      x-accepts: application/json
    patch:
      operationId: user_child_child_id_patch
      parameters:
      - description: Id of the child to update
        explode: false
        in: path
        name: child_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_child_patch_body'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_child_patch_body'
          description: Successfully updated child
      security:
      - bearerAuth: []
      summary: Update the child by id
      x-openapi-router-controller: openapi_server.controllers.child_controller
      x-contentType: application/json
      x-accepts: application/json
  /user/children:
    get:
      operationId: user_children_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/user_child_body'
                type: array
          description: Children of the logged in user
      security:
      - bearerAuth: []
      summary: Get the children of the logged in user
      x-openapi-router-controller: openapi_server.controllers.child_controller
      x-accepts: application/json
  /user/email:
    get:
      operationId: user_email_get
      responses:
        "200":
          content:
            application/json:
              schema:
                example: user@example.com
                type: string
                x-content-type: application/json
          description: Email of the logged in user
      security:
      - bearerAuth: []
      summary: Get the email of the logged in user
      x-openapi-router-controller: openapi_server.controllers.user_controller
      x-accepts: application/json
  /user/invitation:
    post:
      operationId: invitation_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invitation_create_body'
      responses:
        "201":
          description: Successfully sent out the invitation
      security:
      - bearerAuth: []
      summary: Create an invitation and sends out an email to the given email address
      x-openapi-router-controller: openapi_server.controllers.invitation_controller_
      x-contentType: application/json
      x-accepts: application/json
  /user/invitation/{invitation_id}:
    get:
      operationId: invitation_get
      parameters:
      - description: Id of the invitation
        explode: false
        in: path
        name: invitation_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invitation_information_body'
          description: Invitation information
      summary: Get the invitation information with the given ID
      x-openapi-router-controller: openapi_server.controllers.invitation_controller_
      x-accepts: application/json
  /user/invitations:
    get:
      operationId: invitations_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/invitation_information_body'
                type: array
          description: Invitation information
      security:
      - bearerAuth: []
      summary: Get all the invitations of the user
      x-openapi-router-controller: openapi_server.controllers.invitation_controller_
      x-accepts: application/json
  /user/parents:
    get:
      operationId: user_parents_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/user_body'
                type: array
          description: Parents of the logged in user
      security:
      - bearerAuth: []
      summary: Get the parents of the logged in user
      x-openapi-router-controller: openapi_server.controllers.user_controller
      x-accepts: application/json
  /user/subscription:
    post:
      operationId: user_subscription_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_subscription_body'
      responses:
        "200":
          description: Successfully added subscription to the logged in user
      security:
      - bearerAuth: []
      summary: Add a subscription to the logged in user
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
      x-contentType: application/json
      x-accepts: application/json
  /user/subscription/{subscription_id}:
    get:
      operationId: user_subscription_get
      parameters:
      - description: Id of the subscription
        explode: false
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Subscription of the logged in user
      security:
      - bearerAuth: []
      summary: Get the subscription of the logged in user
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
    patch:
      operationId: user_subscription_patch
      parameters:
      - description: Id of the subscription
        explode: false
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Subscriptions end date set
      security:
      - bearerAuth: []
      summary: Set the subscription end date
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
      x-accepts: application/json
  /user/subscriptions:
    get:
      operationId: user_subscriptions_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
                type: array
          description: Subscriptions of the logged in user
      security:
      - bearerAuth: []
      summary: Get the subscriptions of the logged in user
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
      x-accepts: application/json
  /user/{child_id}/subscriptions:
    get:
      operationId: user_child_subscriptions_get
      parameters:
      - description: Id of the child to get
        explode: false
        in: path
        name: child_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
                type: array
          description: Subscriptions of the logged in user
      security:
      - bearerAuth: []
      summary: Get the subscriptions of the logged in user
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
      x-accepts: application/json
components:
  schemas:
    user_body:
      example:
        name: John Doe
        email: xxx@xxx.xx
      properties:
        email:
          type: string
        name:
          type: string
      title: user_body
    invitation_information_body:
      example:
        tenant_id: gid:abcdefghijklmno
        message_attributes:
        - gid:aakkkkaaakkkaa
        reference_id: gid:1111kkkkk1111kkkkk111
        accepted_by: gid:kkkkkkiiiiiikkkkkkk
        expire_time: 2000-01-23T04:56:07.000+00:00
        invite_at_time: 2000-01-23T04:56:07.000+00:00
        state: INVITATION_STATE_ACCEPTED
        invitee: xxx@xxx.xx
      properties:
        accepted_by:
          nullable: true
          type: string
        expire_time:
          format: date-time
          type: string
        invite_at_time:
          format: date-time
          type: string
        invitee:
          type: string
        message_attributes:
          items:
            $ref: '#/components/schemas/invitation_information_body_message_attributes_inner'
          nullable: true
          type: array
        reference_id:
          type: string
        state:
          enum:
          - INVITATION_STATE_INVALID
          - INVITATION_STATE_IN_FUTURE
          - INVITATION_STATE_PENDING
          - INVITATION_STATE_ACCEPTED
          - INVITATION_STATE_EXPIRED
          - INVITATION_STATE_CANCELLED
          type: string
        tenant_id:
          type: string
      title: invitation_information_body
      type: object
    invitation_create_body:
      example:
        invitee: xxx@xxx.xx
      properties:
        invitee:
          format: email
          type: string
      title: invitation_create_body
    user_address_body:
      properties:
        street:
          example: Main St 1
          title: street
          type: string
        city:
          example: Big City
          title: city
          type: string
        country:
          example: USA
          title: country
          type: string
        zip:
          example: "12345"
          title: zip
          type: string
      title: user_address_body
      type: object
    inline_response_200_1:
      example:
        from: 2022-01-01T00:00:00Z
        to: 2022-12-31T23:59:59Z
        sku:
        - SKU22005
        - SKU22005
        child: 123e4567-e89b-12d3-a456-426655440000
      properties:
        from:
          example: 2022-01-01T00:00:00Z
          format: date-time
          type: string
        to:
          example: 2022-12-31T23:59:59Z
          format: date-time
          type: string
        sku:
          items:
            example: SKU22005
            type: string
          type: array
        child:
          example: 123e4567-e89b-12d3-a456-426655440000
          format: uuid
          type: string
      title: inline_response_200_1
      type: object
    inline_response_200:
      example:
        id: 11111111-41111111-81111111-111111111111
        zip: "12345"
        country: USA
        city: Big City
        address: Main Street 1
      properties:
        street:
          example: Main St
          type: string
        number:
          example: 123
          type: integer
        city:
          example: Anytown
          type: string
        state:
          example: CA
          type: string
        zip:
          example: "12345"
          type: string
        country:
          example: USA
          type: string
      title: inline_response_200
      type: object
    user_child_body:
      example:
        shoe_size: 36
        gender: male
        cloth_size: 122
        helmet_size: 52
        given_name: John
        year_of_birth: 2010
      properties:
        given_name:
          example: John
          type: string
        year_of_birth:
          example: "2010"
          type: string
        gender:
          example: male
          type: string
        cloth_size:
          example: "122"
          type: string
        shoe_size:
          example: "36"
          type: string
        helmet_size:
          example: "52"
          type: string
      title: user_child_body
      type: object
    user_child_patch_body:
      example:
        shoe_size: 36
        cloth_size: 122
        helmet_size: 52
      properties:
        cloth_size:
          example: "122"
          type: string
        shoe_size:
          example: "36"
          type: string
        helmet_size:
          example: "52"
          type: string
      title: user_child_patch_body
      type: object
    user_subscription_body:
      properties:
        valid_from:
          example: 2022-01-01T00:00:00Z
          format: date-time
          title: from
          type: string
        valid_to:
          example: 2022-12-31T23:59:59Z
          format: date-time
          title: to
          type: string
        sku:
          items:
            example: SKU22005
            type: string
          title: sku
          type: array
        child:
          example: 123e4567-e89b-12d3-a456-426655440000
          format: uuid
          title: child
          type: string
      title: user_subscription_body
      type: object
    invitation_information_body_message_attributes_inner:
      oneOf:
      - type: string
      - type: integer
      - type: number
      title: invitation_information_body_message_attributes_inner
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller_.info_from_bearerAuth
